---
install_from_src: false
servername: "{{ ansible_default_ipv4.address }}"

clusters:
  slurm: # TODO(gb637) make {{ openhpc_cluster_name }} interporlation work here
    v2:
      metadata:
        title: "{{ openhpc_cluster_name }}"
      login:
        host: "{{ ansible_default_ipv4.address }}"
      job:
        adapter: slurm
        cluster: "{{ openhpc_cluster_name }}"

ood_apps:
  bc_desktop:
    title: Remote Desktop
    description: |
      Request a desktop to run GUI applications.
    cluster: "{{ openhpc_cluster_name }}"
    form:
      - desktop
      - bc_account
      - bc_queue
      - bc_num_hours
      - num_cores
      - bc_email_on_started
      - bc_num_slots
    attributes:
      desktop: xfce

  files:
    env:
      ood_shell: ""

openhpc_module_system_install: false
