---
- name: Run EESSI test job
  hosts: login # TODO: Limit this to single node when there are multiple?
  become: true
  become_user: testuser
  tasks:
    - name: Clone eessi-demo repo
      ansible.builtin.git:
        repo: "https://github.com/eessi/eessi-demo.git"
        dest: ~/eessi-demo

    - name: Run test job
      ansible.builtin.shell:
        cmd: |
          source /cvmfs/pilot.eessi-hpc.org/latest/init/bash
          srun ./run.sh
        chdir: ~/eessi-demo/TensorFlow
        executable: /bin/bash
      register: job_output

    - name: Fail if job output contains error
      fail:
        # Note: Job prints live progress bar to terminal, so use regex filter to remove this from stdout
        msg: "Test job using EESSI modules failed. Job output was: {{ job_output.stdout | regex_replace('\b', '') }}"        
      when: '"Epoch 5/5" not in job_output.stdout'
      