- name: Install ondemand prometheus exporter
  yum:
    name: ondemand_exporter
  when: openondemand_monitoring

- name: Start and enable ondemand prometheus exporter
  service:
    name: ondemand_exporter
    enabled: true
    state: started
