---

- name: Set osc.ood variables from this role's defaults if no overriding inventory var
  set_fact:
    "{{ item.key }}": "{{ lookup('vars', item.key, default=item.value) }}"
  loop: "{{ openondemand_osc_ood_defaults | dict2items }}"
  when: (item.key in hostvars[inventory_hostname]) or (item.value is not none)

- include_role:
    name: osc.ood
  # can't set vars: from a dict hence the workaround above

- name: Ensure post_tasks dirs exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    # - /etc/ood/config/apps/dashboard/initializers
    - /etc/ood/config/locales
    - /etc/ood/config/announcements.d
    - /etc/ood/config/pun/html

- name: Create dashboard additional config directory
  file:
    path: /etc/ood/config/apps/dashboard/initializers
    state: directory
    recurse: yes
    owner: root
    mode: o=rwX,go=rX

- name: Create additional shortcuts in Files app
  template:
    src: files_shortcuts.rb.j2
    dest: /etc/ood/config/apps/dashboard/initializers/ood.rb
    owner: root
    mode: o=rw,go=r
  when: openondemand_filesapp_paths

- name: Copy web page to let users create their home directory
  copy:
    src: missing_home_directory.html
    dest: /etc/ood/config/pun/html/missing_home_directory.html

- name: Create mapping file
  template:
    dest: /etc/grid-security/grid-mapfile
    src: grid-mapfile.j2
    owner: root
    group: apache
    mode: u=rw,g=r,o=
  when: openondemand_mapping_users

# don't think we actually want to *DEFINE* the MOTD from this role.
# However the openondemand_ood_apps.dashboard.env.motd_path variables are probably useful.
# - name: Copy motd
#   template:
#     src: motd
#     dest: /etc/motd

# - name: Ensure ondemand-dex is running and active
#   service:
#     name: ondemand-dex
#     enabled: yes
#     state: stopped
#   when: false

# # TODO: make generic
# - name: Copy UM6P Brand images
#   copy:
#     src: ansible/roles/openondemand/ondemand
#     dest: "{{ item }}"
#   loop:
#     - /var/www/ood/public
#     - /usr/share/ondemand-dex/web/themes/

# - name: Force ondemand scripts to use the right locale
#   copy:
#     content: |
#       LANG=en_US.UTF8
#       # TODO(gb637) this is not nice, not pretty. we need a better solution.
#       # remove this snippet.
#       for user in $(getent group hpc-users | cut -d: -f4 | tr ',' ' ' ); do
#         test -d /home/$user || su -l $user -c exit
#       done
#     dest: /etc/ood/profile

#   # TODO(gb637) make this automatic
# TODO: will be needed if openondemand host is NOT the same as the login node
# - name: Add ssh_known_hosts for login node
#   copy:
#     content: |
#       slurm-login-h23d5-u38-svn1,10.43.1.5 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLRzrCQ/iZYBgpWrdn4o3IdJCuXuAUQHbAllc2jEAtTrnVFL3llhexHpNTAo4Kmw40UCv+/1cSHGieBrsH8i0Ec=
#     dest: /etc/ssh/ssh_known_hosts
#   when: false

