---

- include_role:
    name: osc.ood
  vars:
    httpd_port: "{{ ood_httpd_port }}"
    ssl_cert: "{{ ood_ssl_cert }}"
    ssl_cert_key: "{{ ood_ssl_cert_key }}"
    ssl: "{{ ood_ssl }}"
    
- name: Ensure post_tasks dirs exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    # - /etc/ood/config/apps/dashboard/initializers
    - /etc/ood/config/locales
    - /etc/ood/config/announcements.d
    - /etc/ood/config/pun/html

# TODO: (steveb): find a way to add filesystems to this - by default will just get homedir (https://osc.github.io/ood-documentation/release-1.2/applications/dashboard.html#add-shortcuts-to-files-menu)
# - name: Create files shortcuts
#   copy:
#     content: |
#       OodFilesApp.candidate_favorite_paths.tap do |paths|
#         # add RDS space directories
#         paths << Pathname.new("/srv/data/#{User.new.name}")
#       end
#     dest: /etc/ood/config/apps/dashboard/initializers/ood.rb

- name: Copy web page to let users create their home directory
  copy:
    src: missing_home_directory.html
    dest: /etc/ood/config/pun/html/missing_home_directory.html

- name: Create mapping file
  template:
    dest: /etc/grid-security/grid-mapfile
    src: grid-mapfile.j2
    owner: root
    group: apache
    mode: u=rw,g=r,o=
  when: openondemand_mapping_users

# - name: Create user_map script to make all users lower case
#   copy:
#     content: |
#       #!/bin/bash
#       username=${1,,}
#       shift
#       /opt/ood/ood_auth_map/bin/ood_auth_map.regex ${username} $@
#     dest: "{{ user_map_cmd }}"
#     mode: "0755"
#   when: false

# don't think we actually want to *DEFINE* the MOTD from this role.
# However the openondemand_ood_apps.dashboard.env.motd_path variables are probably useful.
# - name: Copy motd
#   template:
#     src: motd
#     dest: /etc/motd

# - name: Ensure ondemand-dex is running and active
#   service:
#     name: ondemand-dex
#     enabled: yes
#     state: stopped
#   when: false

# # TODO: make generic
# - name: Copy UM6P Brand images
#   copy:
#     src: ansible/roles/openondemand/ondemand
#     dest: "{{ item }}"
#   loop:
#     - /var/www/ood/public
#     - /usr/share/ondemand-dex/web/themes/

# - name: Move favicon to the top level
#   copy:
#     src: /var/www/ood/public/ondemand/favicon.ico
#     dest: "{{ item }}"
#     remote_src: true
#   loop:
#     - /var/www/ood/public/favicon.ico
#     - /usr/share/ondemand-dex/web/themes/ondemand/favicon.svg

# - name: Force ondemand scripts to use the right locale
#   copy:
#     content: |
#       LANG=en_US.UTF8
#       # TODO(gb637) this is not nice, not pretty. we need a better solution.
#       # remove this snippet.
#       for user in $(getent group hpc-users | cut -d: -f4 | tr ',' ' ' ); do
#         test -d /home/$user || su -l $user -c exit
#       done
#     dest: /etc/ood/profile

#   # TODO(gb637) make this automatic
# TODO: will be needed if openondemand host is NOT the same as the login node
# - name: Add ssh_known_hosts for login node
#   copy:
#     content: |
#       slurm-login-h23d5-u38-svn1,10.43.1.5 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLRzrCQ/iZYBgpWrdn4o3IdJCuXuAUQHbAllc2jEAtTrnVFL3llhexHpNTAo4Kmw40UCv+/1cSHGieBrsH8i0Ec=
#     dest: /etc/ssh/ssh_known_hosts
#   when: false
