- hosts: cluster
  become: yes
  tasks:
    - name: check for local munge key
      stat:
        path: ./builder/etc/munge/munge.key
        get_attributes: false
      delegate_to: localhost
      run_once: true
      register: munge_key
    - import_role:
        name: ansible-role-cluster-nfs
      vars:
        nfs_enable:
          server:  "{{ inventory_hostname in groups.get('cluster_login', []) }}"
          clients: "{{ inventory_hostname in groups.get('cluster_compute', []) }}"
        nfs_server: testohpc-login-0
        nfs_export: "/mnt/nfs/"
        nfs_client_mnt_point: "/mnt/nfs/"
        nfs_client_mnt_state: "{{ 'present' if inventory_hostname == 'builder' else 'mounted' }}"
    
    - import_role:
        name: ansible-role-openhpc
      tags:
        - slurm
      vars:
        openhpc_enable:
          control: "{{ inventory_hostname in groups.get('cluster_login', []) }}"
          batch: "{{ inventory_hostname in groups.get('cluster_compute', []) }}"
          runtime: true
        openhpc_slurm_service_started: "{{ false if inventory_hostname == 'builder' else true }}"
        openhpc_slurm_control_host: testohpc-login-0
        openhpc_slurm_partitions:
         - name: "compute"
        openhpc_cluster_name: testohpc
        openhpc_packages: []
        openhpc_slurm_configless: true
        openhpc_munge_key: "{{ munge_key.stat.path if munge_key.stat.exists else '' }}"
