- hosts: cluster
  become: yes
  tasks:
    - import_role:
        name: ansible-role-cluster-nfs # need `nfs_client_mnt_state`
      vars:
        nfs_enable:
          server:  "{{ inventory_hostname in groups['cluster_login'] }}"
          clients: "{{ inventory_hostname in groups['cluster_compute'] }}"
        nfs_server: "{{ groups['cluster_login'] | first }}"
        nfs_export: "/mnt/nfs/"
        nfs_client_mnt_point: "/mnt/nfs/"
    
    - import_role:
        name: ansible-role-openhpc
      tags:
        - slurm
      vars:
        openhpc_enable:
          control: "{{ inventory_hostname in groups['cluster_login'] }}"
          batch: "{{ inventory_hostname in groups['cluster_compute'] }}"
          runtime: true
        openhpc_slurm_service_started: true
        openhpc_slurm_control_host: "{{ groups['cluster_login'] | first }}"
        openhpc_slurm_partitions:
         - name: "compute"
        openhpc_cluster_name: testohpc
        openhpc_packages: []
        openhpc_slurm_configless: true
