# NB: this only works on centos 8 / ohpc v2 as we want UCX
- hosts: all
  become: yes
  tasks:
    - name: Install gnu 9 + openmpi (w/ ucx) + performance tools
      yum:
        name: ohpc-gnu9-openmpi4-perf-tools
        state: present
    - name: Make centos nfs share owner
      file:
        path: /mnt/nfs
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: Create sbatch script for IMB pingpong
      copy:
        dest: "/mnt/nfs//ping.sh"
        content: |
          #!/usr/bin/bash

          #SBATCH --ntasks=2
          #SBATCH --ntasks-per-node=1
          #SBATCH --output=%x.out
          #SBATCH --error=%x.out

          module load gnu9/9.3.0
          module load openmpi4/4.0.4
          module load imb/2019.6

          srun --mpi=pmix_v3 IMB-MPI1 pingpong
      run_once: True
    - name: Run pingpong
      shell: sbatch ping.sh
      become: no
      args:
        chdir: "/mnt/nfs/"
    
    # TODO: retrieve results
