---

# See ansible/roles/mysql for variable definitions.

# The user which runs the mysql container
mysql_podman_user: podman

# Slurm recommends larger than default values: https://slurm.schedmd.com/accounting.html
mysql_mysqld_options:
  - innodb-buffer-pool-size=1024M
  - innodb-lock-wait-timeout=900

mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_datadir: "{{ appliances_state_dir | default('/var/lib') }}/mysql"

mysql_databases:
  - name: slurm_acct_db
    config_file: ''

mysql_users:
  - name: slurm
    host: "%"
    password: "{{ vault_mysql_slurm_password }}"
    priv: "slurm_acct_db.*:ALL"
