---
## TODO: most of this needs namespacing properly :-(
## TODO: maybe we should arrange it following the osc.github.io docs
## TODO: Note the varible names (except ones we've namespaced!) come from https://github.com/OSC/ood-ansible

#sssd_allow_groups: hpc-admins
# openondemand_servername: "{{ ansible_default_ipv4.address }}" # TODO: probably need to make this more complex like api etc
# httpd_use_rewrites: false
# httpd_port: 80
#ssl:
#  - 'SSLCertificateFile "{{ ood_ssl_cert_file }}"'
#  - 'SSLCertificateKeyFile "{{ ood_ssl_cert_file_key }}"'
#  - 'SSLCipherSuite AES256+EECDH:AES256+EDH:AES128+EECDH:AES128+EDH'
#  - 'SSLProtocol -ALL -SSLv3 +TLSv1.2'
#  - 'SSLHonorCipherOrder on'
#  - 'SSLStrictSNIVHostCheck off'
#  - 'SSLCompression off'
#  - 'SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire'
#  - 'Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"'
#  - 'Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure'
#  - 'Header always set X-Frame-Options SAMEORIGIN'

#httpd_auth:
#  - 'AuthType openid-connect'
#  - 'Require valid-user'

# I don't think we even need dex, can set ood_auth_openidc directly?
# install_ondemand_dex: true
# dex_settings: # https://osc.github.io/ood-documentation/latest/authentication/dex.html#dex-configuration
#   dex:
#     connectors:
#       - type: oidc  # https://dexidp.io/docs/connectors/oidc/
#         id: TODO
#         name: TODO
#         config:
#           issuer: TODO
#           clientID: TODO
#           clientSecret: TODO
#           redirectURI: TODO
#           scopes: [] # not sure we need any?
#             #- 'federated:id'
#           promptType: consent # TODO see what returns
#    frontend:
#      dir: /usr/share/ondemand-dex/web
#      issuer: TODO_ADD_DEX_ISSUER
#      extra:
#         loginButtonText: TODO_ADD_LOGIN_BUTTON_TEXT

# OpenID Connect config - see https://github.com/OSC/ood-ansible#open-id-connect
# See environments/alaska-common/inventory/group_vars/openondemand.yml
# ood_auth_openidc:


# ood_auth_openidc:
#   OIDCRedirectURI: "https://{{ openondemand_servername }}/oidc"  # for some reason this gets ignored on merging!
#   OIDCClientID: 248626ed-3553-47a0-86f0-7d2b51421cb0
#   OIDCClientSecret: ALj4EbEct1OMzx18aykn2d0Xkk0Hq3YwBoJcwQD_syhk5RrfcpfaRH0voiCXYk3RWNyxSzt5AF75ldYzQcBWBsg
#   OIDCProviderMetadataURL: https://iris-iam.stfc.ac.uk/.well-known/openid-configuration
#   OIDCCryptoPassphrase: oq1uGEj5dQMmr/N9WiLGgSJbmYkUPx5jyXA/ujA1ctxpMjonFq5mP7Do5OhXyaRuEpDYsOT8RCUYO0l6c6TfZ6TY # TODO: generate in passwords
#   OIDCSSLValidateServer: Off

# Reverse Proxy config: https://osc.github.io/ood-documentation/latest/reference/files/ood-portal-yml.html#configure-reverse-proxy
# node_uri: /node
# rnode_uri: /rnode

# https://github.com/OSC/ood-ansible#clusters
openondemand_clusters:
  slurm:
    v2:
      metadata:
        title: "{{ openhpc_cluster_name }}" # interpolation here works as openondemand is lexically after openhpc
      login:
        host: "{{ ansible_default_ipv4.address }}" # TODO: should be specific interface of first LOGIN node - by default
        default: true
      job:
        adapter: slurm
        cluster: "{{ openhpc_cluster_name }}"
      batch_connect:
        basic:
          script_wrapper: |
            module purge
            %s
          set_host: host=$(hostname -s)
        vnc:
          script_wrapper: |
            module purge
            export PATH=/opt/TurboVNC/bin:$PATH
            export WEBSOCKIFY_CMD=/bin/websockify

            # Workaround to avoid "Unable to contact settings server" when
            # lauching xfce4-session
            xfce4-session() { /bin/dbus-launch /bin/xfce4-session $@ ; }
            export -f xfce4-session
            %s
          set_host: host=$(hostname -s)

# https://github.com/OSC/ood-ansible#ood_apps
ood_apps:
  bc_desktop:
    title: Remote Desktop
    description: |
      Request a desktop to run GUI applications.
    cluster: "{{ openhpc_cluster_name }}"
    form:
      - desktop
      - bc_account
      - bc_queue
      - bc_num_hours
      - num_cores
      - bc_email_on_started
      - bc_num_slots
      - node
    attributes:
      desktop: xfce
      bc_account:
        value: root
      bc_queue:
        value: compute
      num_cores:
        min: 1
      node: ""
    submit: |
      ---
      script:
        native:
          - <%= "--nodes=#{bc_num_slots}" %>
          - <%= "--ntasks=#{num_cores}" %>
          - <%= "--nodelist=#{node}" %>

  dashboard:
    env:
      motd_path: /etc/motd
      motd_format: markdown
      ood_dashboard_support_url: mailto:support-hpc@um6p.ma
      ood_dashboard_docs_url: https://crc4.gitlab.io/um6p/operations/um6p-sysops
      ood_brand_bg_color: "#0e6ec8"
      ood_dashboard_title: ASCC
      ood_dashboard_logo: /public/ondemand/logo.png
      ood_dashboard_headr_img_logo: /public/ondemand/logo.png
      ood_dashboard_logo_height: 200px

  files:
    env:
      ood_shell: ""

  shell:
    env:
      ood_shell_origin_check: "off" # "http://{{ openondemand_servername }}"

user_map_cmd: /opt/ood/ood_auth_map/bin/ood_auth_map.mapfile
