---
## TODO: maybe we should arrange it following the osc.github.io docs
## TODO: Note the varible names GENERALLY come from https://github.com/OSC/ood-ansible

user_map_cmd: /opt/ood/ood_auth_map/bin/ood_auth_map.mapfile
