---
## TODO: maybe we should arrange it following the osc.github.io docs
## NB: Variables prefixed ood_ are all from https://github.com/OSC/ood-ansible

openondemand_clusters:
  slurm:
    v2:
      metadata:
        title: "{{ openhpc_cluster_name }}" # interpolation here works as openondemand is lexically after openhpc
      login:
        host: "{{ hostvars[groups['login'].0].api_address }}"
        default: true
      job:
        adapter: slurm
        cluster: "{{ openhpc_cluster_name }}"
      batch_connect:
        basic:
          script_wrapper: |
            module purge
            export PATH=/opt/jupyter/bin/:$PATH
            %s
        vnc:
          script_wrapper: |
            module purge

            export PATH=/opt/TurboVNC/bin:$PATH

            # Workaround to avoid "Unable to contact settings server" when
            # lauching xfce4-session
            xfce4-session() { /bin/dbus-launch /bin/xfce4-session $@ ; }
            export -f xfce4-session
            %s
          set_host: host=$(hostname -s)
      # TODO: add grafana in here - see https://osc.github.io/ood-documentation/latest/customization.html#grafana-support

ood_install_apps:
  jupyter:
    repo: https://github.com/OSC/bc_example_jupyter.git
    dest: "{{ ood_sys_app_dir }}"  # defaults (optional)
    version: master                # defaults (optional)

ood_apps: # osc.ood:ood_apps - see https://github.com/OSC/ood-ansible#ood_apps
# see https://osc.github.io/ood-documentation/latest/enable-desktops/custom-job-submission.html#enable-desktops-custom-job-submission
  bc_desktop: # https://github.com/OSC/ondemand/tree/master/apps/bc_desktop # TODO: only add this when hosts in openondemand_vnc?
    title: Remote Desktop
    description: |
      Request a desktop to run GUI applications.
    cluster: slurm
    form:
      - desktop
      - bc_queue
      - bc_num_hours
      - num_cores
      - node
    attributes:
      desktop: xfce
      # bc_account: # i.e. slurm account
      #   value: root
      bc_queue:
        value: "{{ openondemand_desktop_partition }}"
      num_cores:
        label: Number of cores
        min: 1
      node:
        label: Node name
        help: Select a particular node or leave empty to let Slurm pick the next available
        value: ""
    submit: |
      ---
      script:
        job_name: "ood-desktop"
        native:
          - <%= "--nodes=1" %>
          - <%= "--ntasks=#{num_cores}" %>
          - <%= "--nodelist=#{node}" %>
  files:
    env:
      ood_shell: ""
  shell:
    env:
      ood_shell_origin_check: "off" # "http://{{ openondemand_servername }}"
  dashboard:
    env:
      motd_path: /etc/motd
      motd_format: markdown
      ood_dashboard_support_url: "{{ openondemand_dashboard_support_url }}"
      ood_dashboard_docs_url: "{{ openondemand_dashboard_docs_url }}"
      ood_brand_bg_color: "#0e6ec8"
      ood_dashboard_title: "{{ openhpc_cluster_name }}"
  jupyter:
    title: Jupyter Notebook
    description: Request a Jupyter Notebook
    cluster: slurm
    form:
      - modules
      - extra_jupyter_args
      - bc_queue
      - bc_num_hours
      - num_cores
      - node
    attributes: # TODO
      num_cores:
        label: Number of cores
        value: 1
      modules: ""
      extra_jupyter_args: ""
      bc_queue:
        value: "{{ openondemand_desktop_partition }}" # TODO: somewhere else??
      node: ""
    submit: |
      ---
      batch_connect:
        template: "basic"
      script:
        job_name: "ood-jupyter"
        native:
          - <%= "--nodes=1" %>
          - <%= "--ntasks=#{num_cores}" %>
          - <%= "--nodelist=#{node}" %>
    
# Prometheus config for Open Ondemand exporter
# https://osc.github.io/ood-documentation/latest/monitoring/prometheus.html#prometheus-configuration
openondemand_scrape_configs:
  - job_name: ondemand
    metrics_path: /metrics
    scrape_timeout: 20s
    scrape_interval: 2m
    static_configs:
    - targets:
      - "{{ openondemand_address }}:9301"
      labels:
        environment: "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_NAME') }}"
        service: "openondemand"

openondemand_dashboard:
  - dashboard_id: 13465
    replacements:
      - placeholder: DS_PROMETHEUS
        replacement: prometheus
    revision_id: 1
