---
## TODO: maybe we should arrange it following the osc.github.io docs
## NB: Variables prefixed ood_ are all from https://github.com/OSC/ood-ansible

openondemand_clusters:
  slurm:
    v2:
      metadata:
        title: "{{ openhpc_cluster_name }}" # interpolation here works as openondemand is lexically after openhpc
      login:
        host: "{{ ansible_default_ipv4.address }}" # TODO: should be specific interface of first LOGIN node - by default
        default: true
      job:
        adapter: slurm
        cluster: "{{ openhpc_cluster_name }}"
      batch_connect:
        basic:
          script_wrapper: |
            module purge
            %s
        vnc: # TODO: check/fix
          script_wrapper: |
            module purge
            export PATH=/opt/TurboVNC/bin:$PATH

            # Workaround to avoid "Unable to contact settings server" when
            # lauching xfce4-session
            xfce4-session() { /bin/dbus-launch /bin/xfce4-session $@ ; }
            export -f xfce4-session
            %s
          set_host: host=$(hostname -s)
          # TODO: add grafana in here - see https://osc.github.io/ood-documentation/latest/customization.html#grafana-support

ood_apps: # osc.ood:ood_apps - see https://github.com/OSC/ood-ansible#ood_apps
  bc_desktop:             # TODO: get this working
    title: Remote Desktop
    description: |
      Request a desktop to run GUI applications.
    cluster: slurm
    form:
      - desktop
      # - bc_account
      - bc_queue
      - bc_num_hours
      - num_cores
      # - bc_email_on_started
      - bc_num_slots
      - node
    attributes:
      desktop: xfce
      # bc_account:
      #   value: root
      bc_queue:
        value: small # TODO: this isn't necessarily correct
      num_cores:
        min: 1
      node: ""
    submit: |
      ---
      script:
        job_name: "ood-desktop"
        native:
          - <%= "--nodes=#{bc_num_slots}" %>
          - <%= "--ntasks=#{num_cores}" %>
          - <%= "--nodelist=#{node}" %>
  files:
    env:
      ood_shell: ""
  shell:
    env:
      ood_shell_origin_check: "off" # "http://{{ openondemand_servername }}"
  dashboard:
    env:
      motd_path: /etc/motd
      motd_format: markdown
      ood_dashboard_support_url: "{{ openondemand_dashboard_support_url }}"
      ood_dashboard_docs_url: "{{ openondemand_dashboard_docs_url }}"
      ood_brand_bg_color: "#0e6ec8"
      ood_dashboard_title: "{{ openhpc_cluster_name }}"
      ood_dashboard_logo: /var/www/ood/public/logo.png
      ood_dashboard_headr_img_logo: /var/www/ood/public/logo.png
      ood_dashboard_logo_height: 200px
