---
- name: Ensure parent directory exists
  file:
    state: directory
    path: "/etc/filebeat"
    owner: "1000"
    group: "1000"
    mode: 0770
  become: true

- name: Template configuration files
  template:
      src: "{{ filebeat_config_path }}"
      dest: /etc/filebeat/filebeat.yml
      owner: "1000"
      group: "1000"
      mode: 0600
  notify: Restart filebeat container
  become: true
