---
- name: Create data directory
  file:
    path: "{{ opensearch_data_path }}"
    state: directory
    owner: "{{ opensearch_podman_user }}"
    group: "{{ opensearch_podman_user }}"
  become: true
  notify: Restart opensearch container

- name: Create systemd unit file
  template:
    dest: /etc/systemd/system/opensearch.service
    src: opensearch.service.j2
  become: true
  notify: Restart opensearch container
