---

nfs_server_default: "{{ hostvars[groups['control'] | first ].internal_address }}"

nfs_configuration:
  nfs_enable:
      server:  "{{ inventory_hostname in groups['control'] }}"
      clients: "{{ inventory_hostname in groups['computes'] or inventory_hostname in groups['login']  }}"
  nfs_server: "{{ nfs_server_default }}"
  nfs_export: "/mnt/nfs/"
  nfs_client_mnt_point: "/mnt/nfs/"