---

nfs_server_default: "{{ hostvars[groups['control'] | first ].internal_address }}"

nfs_configurations:
  - nfs_enable:
      server:  "{{ inventory_hostname in groups['control'] | first }}"
      clients: "{{ inventory_hostname in groups['computes'] or inventory_hostname in groups['login']  }}"
    nfs_server: "{{ nfs_server_default }}"
    nfs_export: "/mnt/nfs/"
    nfs_client_mnt_point: "/mnt/nfs/"
  # Currently /opt is assumed to exist on a shared FS. You can override
  # nfs_configurations to remove this entry if required.
  - nfs_enable:
      server:  "{{ inventory_hostname in groups['control'] | first }}"
      clients: "{{ inventory_hostname in groups['computes'] or inventory_hostname in groups['login'] }}"
    nfs_server: "{{ nfs_server_default }}"
    nfs_export: "/opt"
    nfs_client_mnt_point: "/opt"