- name: Ensure freeipa_server_ip is first in freeipa_client host's resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: nameserver {{ freeipa_server_ip }}
    firstmatch: true
    insertbefore: '^nameserver'

- name: Add host to IPA
  # annoyingly this always shows as changed!
  community.general.ipa_host:
    name: "{{ [inventory_hostname, openhpc_cluster_name, tld] | join('.') }}" # don't want to use ansible_ variables as might not have host in play e.g. during image build
    ip_address: "{{ freeipa_client_ip }}"
    ipa_host: "{{ groups['freeipa_server'].0 }}"
    ipa_pass: "{{ vault_freeipa_admin_password }}"
    ipa_user: admin
    random_password: true
    state: present
    validate_certs: false
  delegate_to: "{{ groups['freeipa_server'].0 }}"
  register: _ipa_host_add

- name: Set fact for ipa host password
  set_fact:
    freeipa_host_password: "{{ _ipa_host_add.host.randompassword }}"
