# based on https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/assembly_installing-an-idm-client_installing-identity-management

- name: Install FreeIPA client package
  dnf:
    name: ipa-client

- name: Set IPA server as nameserver
  copy:
    dest: /etc/resolv.conf
    content: |
      ; Created by slurm appliance/ansible/roles/freeipa/tasks/client.yml
      ;

      nameserver {{ freeipa_server_ip }}
      nameserver 131.111.12.20
    owner: root
    group: root
    mode: u=rw,og=r

- name: Enrole with FreeIPA
  # reenrolment requires --force-join and --password or --keytab
  # renrolement means:
  #  1. A new host certificate is issued
  #  2. The old host certificate is revoked
  #  3. New SSH keys are generated
  #  4. ipaUniqueID is preserved
  # --password is overloaded - its bulkpassword unless --prinicpal is used in which case it's admin password
  command: >
    ipa-client-install
      --unattended
      --mkhomedir
      --force-join
      --enable-dns-updates
      --principal admin
      --password {{ freeipa_admin_password | quote }}
  register: ipa_client_install
  changed_when: ipa_client_install.rc == 0
  failed_when: >
    ipa_client_install.rc != 0 and
    'IPA client is already configured' not in ipa_client_install.stderr
