- name: Ensure incompatible functionality is not enabled
  assert:
    that: groups[item] | length == 0
    fail_msg: "The group {{ item }} contains hosts - this cannot be used with freeipa enabled"
  loop:
    - basic_users
    - etc_hosts
  run_once: yes

- name: Get hostname as reported by command
  command: hostname
  register: _freeipa_validate_hostname
  changed_when: false

- name: Ensure hostname is fully-qualified
  # see section 2.7 of redhat guide to installing identity management
  assert:
    that: _freeipa_validate_hostname.stdout | split('.') | length >= 3
    fail_msg: "Hostname {{ _freeipa_validate_hostname.stdout }} is not fully-qualified (a.b.c)"
