---

- name: Collect usernamespace facts
  user_namespace_facts:

- name: Set facts containing group_ids
  set_fact:
    # Elastic search user is 1000
    opendistro_host_user_id: "{{ ansible_facts.subuid[opendistro_podman_user]['start'] + 1000 - 1 }}"
    opendistro_host_group_id: "{{ ansible_facts.subgid[opendistro_podman_user]['start'] + 1000 - 1 }}"

- name: Ensure parent directory exists
  file:
    state: directory
    path: "/etc/elastic"
    owner: "{{ opendistro_host_user_id }}"
    group: "{{ opendistro_host_group_id }}"
    mode: 0770
  become: true

- name: Template configuration files
  template:
      src: "{{ opendistro_internal_users_path }}"
      dest: /etc/elastic/internal_users.yml
      owner: "{{ opendistro_host_user_id }}"
      # NOTE: root user in container maps to user on host, so this will appear as
      # owned by root in the container.
      group: "{{ opendistro_podman_user }}"
      mode: 0660
  # This needs to smarter as bcrypt hash changes everytime
  notify: Restart opendistro container
  become: true
