- hosts: control:!builder
  become: yes
  gather_facts: false
  tasks:
    - name: Write CI-generated inventory and secrets for debugging
      ansible.builtin.copy:
        dest: /etc/ci-config/
        src: "{{ item }}"
        directory_mode: 0400
        mode: 0400
        owner: root
        group: root
      no_log: true
      loop:
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/hosts"
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/all/secrets.yml"
        - "{{ lookup('env', 'APPLIANCES_ENVIRONMENT_ROOT') }}/inventory/group_vars/all/test_user.yml"

- hosts: all:!builder
  become: yes
  gather_facts: false
  name: Use local container image registry to avoid docker.io ratelimits
  tasks:
    - name: Copy registries.conf
      copy:
        remote_src: true
        src: /etc/containers/registries.conf
        dest: /etc/containers/registries.conf.orig
    - name: Define local registry
      tags: podman
      blockinfile:
        path: /etc/containers/registries.conf
        block: |
          [[registry]]
          prefix = "192.168.3.95:5000"
          location = "192.168.3.95:5000"
          insecure = true
    - name: Use local registry for unqualified searches
      tags: podman
      community.general.ini_file: # actually TOML but this is OK here
        path: /etc/containers/registries.conf
        section: null
        option: unqualified-search-registries
        value: ['192.168.3.95:5000', 'registry.access.redhat.com', 'registry.redhat.io', 'docker.io']
