# Migrates data from containerised opendistro v1.12.0 to containerised opensearch 2.1.0
#
# Usage:
#
#   git pull                # and merge etc as required, including changing groups file to define opensearch not opendistro
#   ansible-playbook ansible/adhoc/migrate-opendistro.yml
#   ansible-playbook ansible/monitoring.yml
#

- hosts: opensearch
  become: no
  gather_facts: no
  tasks:
    - name: Export opendistro volume
      import_role:
        name: opensearch
        tasks_from: migrate-opendistro.yml
