# Clean up a Packer build VM

- meta: flush_handlers

- name: Remove dnf caches
  command: dnf clean all

# If image build happens on a Neutron subnet with property dns_namservers defined, then cloud-init
# disables NetworkManager's control of /etc/resolv.conf and appends nameservers itself.
# We don't want network configuration during instance boot to depend on the configuration
# of the network the builder was on, so we reset these aspects.
- name: Delete /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  when: "'resolv_conf' not in group_names" # if its been overriden, deleting it is the wrong thing to do

- name: Reenable NetworkManager control of resolv.conf
  # NB: This *doesn't* delete the 90-dns-none.conf file created by the resolv_conf role
  # as if nameservers are explicitly being set by that role we don't want to allow NM
  # to override it again.
  file:
    path: /etc/NetworkManager/conf.d/99-cloud-init.conf
    state: absent

- name: Delete any injected ssh config for ansible_user
  file:
    path: "/home/{{ ansible_user }}/.ssh/"
    state: absent

# A podman pause process is started by `podman pull`, and causes an error
#   Error: cannot re-exec process to join the existing user namespace
# in podman commands in the booted image due to its pidfile.
# Later podman versions may cleanup the pidfile automatically.
# NB: This hard-codes the default config that only `podman` user (=1001) runs containers.
- name: Check for running podman containers
  command:
    cmd: podman ps
  become_user: podman
  register: podman_ps
  changed_when: false

- name: Ensure no containers are running
  assert:
    that: podman_ps.stdout_lines | length == 1 # header only
    fail_msg: "podman user has running containers:\n{{ podman_ps.stdout }}"

- name: Get PID of podman pause process
  command:
    cmd: cat /tmp/podman-run-1001/libpod/tmp/pause.pid
  register: podman_pause_pidfile
  changed_when: false

- name: Kill pause process
  command:
    cmd: "kill {{ podman_pause_pidfile.stdout }}"
  become_user: podman

- name: Remove pause pidfile
  file:
    path: /tmp/podman-run-1001/libpod/tmp/pause.pid
    state: absent

- name: Run cloud-init cleanup
  command: cloud-init clean --logs --seed
