- hosts: freeipa_server
  tags:
    - freeipa
    - freeipa_server
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: freeipa
        tasks_from: users.yml

- hosts: freeipa_client
  tags:
    - freeipa
    - freeipa_client
  gather_facts: yes
  become: yes
  tasks:
    - import_role:
        name: freeipa
        tasks_from: client.yml

- hosts: basic_users
  become: yes
  tags:
    - basic_users
  gather_facts: yes
  tasks:
    - import_role:
        name: basic_users
