- hosts: basic_users
  become: yes
  tags:
    - basic_users
  gather_facts: yes
  tasks:
    - import_role:
        name: basic_users

- hosts: openondemand
  tags:
    - openondemand
  become: yes
  gather_facts: yes # TODO
  tasks:
    - import_role:
        name: openondemand
        