---

- name: Setup DB
  hosts: mysql
  become: true
  tags:
    - mysql
  tasks:
    - include_role:
        name:  mysql

- name: Setup slurm-driven reimage
  hosts: rebuild
  become: yes
  tags:
    - rebuild
    - openhpc
  tasks:
    - import_role:
        name: stackhpc.slurm_openstack_tools.rebuild

- name: Workaround https://github.com/openhpc/ohpc/issues/1644
  hosts: compute
  become: yes
  gather_facts: no
  tasks:
    - name: Install old apptainer version to unbreak ohpc-base-compute package
      dnf:
        name: https://github.com/apptainer/apptainer/releases/download/v1.1.3/apptainer-1.1.3-1.x86_64.rpm
        disable_gpg_check: true

- name: Setup slurm
  hosts: openhpc
  become: yes
  tags:
    - openhpc
  tasks:
    - import_role:
        name: stackhpc.openhpc

- name: Set locked memory limits on user-facing nodes
  hosts:
    - compute
    - login
  become: yes
  tags:
    - openhpc
  tasks:
    - name: set memory limits
      lineinfile:
        path: /etc/security/limits.conf
        regexp: '\* soft memlock unlimited'
        line: "* soft memlock unlimited"

- name: Block ssh to compute nodes for non-privileged users without running jobs
  hosts: compute
  become: yes
  tags:
    - openhpc
  tasks:
    - name: Configure sshd pam module
      blockinfile:
        path: /etc/pam.d/sshd
        insertafter: 'account\s+required\s+pam_nologin.so'
        block: |
          account    sufficient   pam_access.so
          account    required     pam_slurm.so
    - name: Configure login access control
      blockinfile:
        path: /etc/security/access.conf
        block: |
          +:wheel:ALL
          +:{{ ansible_user }}:ALL
          -:ALL:ALL
      # vagrant uses (deprecated) ansible_ssh_user
