---

- name: Wait for kibana to start listening
  wait_for:
    host: "{{ kibana_address }}"
    port: "{{ kibana_port }}"
    delay: 5

- name: Wait for kibana to be ready
  uri:
    url: http://{{ kibana_address }}:{{ kibana_port }}/api/kibana/settings
    method: GET
    user: "{{ kibana_admin_user }}"
    password:  "{{ kibana_admin_password }}"
    force_basic_auth: yes
  register: response
  until: "'kbn_name' in response and response.status == 200"
  retries: 30
  delay: 5

- name: Add indexes to kibana
  uri:
    url: "http://{{ kibana_address }}:{{ kibana_port }}/api/saved_objects/index-pattern/{{ index.name }}?overwrite=true"
    method: POST
    user: "{{ kibana_admin_user }}"
    password: "{{ kibana_admin_password }}"
    force_basic_auth: yes
    body_format: json
    body: "{{ index.definition }}"
    headers:
      kbn-xsrf: anything
  loop: "{{ kibana_indexes }}"
  loop_control:
    loop_var: index