- name: Shut down slurm
  systemd:
    name: "{{ item }}"
    state: stopped
  register: _stop
  failed_when: "'msg' in _stop and 'Could not find the requested service' not in _stop.msg"
  # ignore_errors: true
  loop:
    - slurmd
    - slurmctld
    - slurmdbd

- name: Ensure backup directory exists
  file:
    path: "{{ cve_2023_41914_mysql_backup_path | dirname }}"
    state: directory
    owner: root
    group: root
  when: openhpc_enable.control | default(false) | bool

- name: Ensure mysqldump tool installed
  dnf:
    name: mysql
  when: openhpc_enable.control | default(false) | bool

- name: Backup database
  community.mysql.mysql_db:
    name: slurm_acct_db
    state: dump
    target: "{{ cve_2023_41914_mysql_backup_path }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ mysql_host }}"
  when: openhpc_enable.control | default(false) | bool
