
name: Test vagrant with ansible
on: [push]
jobs:
  vagrant-example:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: dev/setup-env.sh

      - name: Activate python environment
        run: . venv/bin/activate

      - name: Activate slurm environment
        run: . environments/vagrant-example/activate

      - name: Install required vagrant plugins
        run: vagrant plugin install vagrant-hosts

      - name: Provision machines
        run: vagrant up
        working-directory: environments/vagrant-example/vagrant

      - name: Create inventory
        run: vagranttoansible | tee $APPLIANCES_ENVIRONMENT_ROOT/inventory/hosts
        working-directory: environments/vagrant-example/vagrant

      - name: Run ansible
        run: ansible ansible/adhoc/generate-secrets.yml

      - name: Run ansible
        run: ansible ansible/site.yml
